# Permalinks
permalink:           pretty

# Setup
title:               Richard's Data Science
tagline:             Understanding the world through data
url:                 rikunert.github.io
paginate:            1
baseurl:             "" #http://github.com/rikunert/rikunert.github.io/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Richard Kunert
  url:               https://twitter.com/rikunert
  email:             rikunert@gmail.com

# Custom vars
version:             2.0.0
github:              https://github.com/rikunert
repo:                https://github.com/rikunert/rikunert.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

future:               true
pages_list:
  About: '/about'
  CV: '/CV'
  Publications: '/Publications'
  Archive: '/archive'
  Feed: '/atom.xml'
excerpt_separator: "<!--excerpt-->"
